language: node_js
node_js:
  - "0.10"
branches:
  only:
    - Travis
install:
  - npm install phantomjs -g
  - npm install -g mocha-phantomjs
  - npm install -g gulp
  - npm install -g bower
before_script:
  - phantomjs --version
  - mocha-phantomjs --version
  - gulp &
  - sleep 5 # give gulp background task some time to execute.
script:
  - mocha-phantomjs /test.js
  - make test